New Community partner PLUG
Schrodinger-Hat/schrodinger-hat-website pull request #41
Opened 2023-01-03 08:24 UTC by nicpuppa

Closes #40

2023-01-03 08:25 UTC, davideimola approved these changes

2023-01-10 11:49 UTC, davideimola requested changes
LGTM

2023-01-10 11:49 UTC, davideimola approved these changes

2023-01-10 13:12 UTC, AngyDev approved these changes

2023-01-10 13:13 UTC, merged